Repository meritlabs/merit, pull requests merged in 2018-02, with the labels that each got.

#230 Enhance mining interface
  src/miner.cpp
  src/rpc/mining.cpp
Labels: bug, enhancement, ready for review

#195 Bucket mining
  src/cuckoo/mean_cuckoo.cpp
  src/init.cpp
  src/miner.cpp
  src/miner.h
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/wallet/rpcwallet.cpp
Labels: ready for review

#224 Always flush blocks to disk after ActivateBestChain
  src/validation.cpp
Labels: bug, ready for review

#221 Initial work on doing validation sampling.
  src/init.cpp
  src/miner.cpp
  src/net_processing.cpp
  src/qt/clientmodel.cpp
  src/qt/forms/modaloverlay.ui
  src/qt/modaloverlay.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/rpc/mining.cpp
  src/test/miner_tests.cpp
  src/test/test_merit.cpp
  src/txdb.cpp
  src/txdb.h
  src/validation.cpp
  src/validation.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: ready for review

#234 OSX code signing
  Makefile.am
  contrib/code-signing/sign-osx.sh
  share/qt/Info.plist.in
Labels: ready for review

#237 Fix alignment on toolbar buttons to be consistent when selected
  src/qt/meritgui.cpp
Labels: ready for review

#236 Allow network and transaction listviews to scroll
  src/qt/forms/overviewpage.ui
  src/qt/overviewpage.cpp
Labels: ready for review

#238 Signing windows packages
  contrib/code-signing/sign-windows.sh
Labels: ready for review, windows

#229 Code cleanup, pt.1
  .gitignore
  contrib/static_check.sh
  src/base58.cpp
  src/base58.h
  src/consensus/merkle.cpp
  src/cuckoo/miner.cpp
  src/cuckoo/miner.h
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/policy/fees.cpp
  src/qt/referrallistmodel.cpp
  src/rpc/rawtransaction.cpp
  src/script/script.cpp
  src/script/script.h
  src/script/sign.cpp
  src/test/bloom_tests.cpp
  src/txdb.cpp
  src/validation.cpp
  src/validation.h
Labels: enhancement, ready for review

#241 Fix use of invalidated iterator which can cause a crash.
  src/net.cpp
  src/net_processing.cpp
  src/primitives/referral.cpp
Labels: bug, ready for review

#240 qt improvements - update overview labels
  src/qt/forms/overviewpage.ui
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: ready for review

#243 Bug/fix cmpctblock protocol
  src/blockencodings.cpp
  src/net_processing.cpp
  src/validation.h
Labels: bug, major, ready for review

#210 Daedalus changes for MWS
  src/addressindex.h
  src/core_io.h
  src/core_write.cpp
  src/miner.cpp
  src/primitives/transaction.cpp
  src/refdb.cpp
  src/refmempool.cpp
  src/refmempool.h
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/rawreferral.cpp
  src/rpc/rawtransaction.cpp
  src/txmempool.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/wallet.cpp
Labels: ready for review

#242 Qt - disable hiding blockchain syncing modal
  src/Makefile.qt.include
  src/qt/forms/modaloverlay.ui
  src/qt/merit.qrc
  src/qt/meritgui.cpp
  src/qt/meritgui.h
  src/qt/modaloverlay.cpp
  src/qt/modaloverlay.h
  src/qt/res/icons/hourglass.png
  src/qt/res/src/hourglass.svg
Labels: ready for review

#244 Qt - show your merit network info
  src/qt/forms/overviewpage.ui
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: ready for review

#245 Peer requests mempool on startup.
  src/net_processing.cpp
  src/rpc/blockchain.cpp
Labels: bug, enhancement, ready for review

#247 Make sure alias have at least 3 characters.
  src/primitives/referral.cpp
Labels: bug, ready for review

#249 Qt - disable mining not confirmed wallets
  src/qt/meritgui.cpp
  src/qt/meritgui.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: ready for review

#252 Qt - show more invite requests
  src/qt/overviewpage.cpp
Labels: Qt Wallet, ready for review

#253 Bug - Clicking dock icon on osx does not restore minimized application
  src/qt/macdockiconhandler.mm
Labels: Qt Wallet, bug, osx, ready for review

#251 Qt - add basic tooltips to labels on overview page
  src/qt/forms/overviewpage.ui
Labels: Qt Wallet, ready for review

#254 Added a better message about inviting users.
  src/Makefile.qt.include
  src/qt/forms/overviewpage.ui
  src/qt/merit.qrc
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/res/icons/spread.png
  src/qt/res/src/invite-spread.svg
Labels: enhancement, ready for review

#258 Do not generate new hd key on wallet encryption
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: ready for review

#260 Adding more DNS seeds.
  src/chainparams.cpp
Labels: ready for review

#263 Fix the messaging to be more accurate.
  src/qt/forms/modaloverlay.ui
Labels: enhancement, ready for review

#264 Fix segfault on referrals mempool reorg
  src/validation.cpp
Labels: bug, ready for review

#262 The assert detected a bad db state.
  src/refdb.cpp
Labels: bug, ready for review
