Repository meritlabs/merit, pull requests merged in 2018-05, with the labels that each got.

#338 Fix undoing indexing during disconnect block.
  src/addressindex.h
  src/validation.cpp
Labels: bug, major, ready for review

#339 Better Invite Distribution
  src/Makefile.am
  src/chainparams.cpp
  src/consensus/params.h
  src/miner.cpp
  src/pog/invitebuffer.cpp
  src/pog/invitebuffer.h
  src/pog/reward.cpp
  src/pog/reward.h
  src/validation.cpp
  src/validation.h
Labels: In Testing, enhancement, major, ready for review

#340 Blocktimeout should be 10080, not 1008.
  src/wallet/rpcwallet.cpp
Labels: ready for review

#342 Use red for outgoing transactions.
  src/qt/guiconstants.h
  src/qt/overviewpage.cpp
Labels: enhancement, ready for review, usability

#343 Include ancestors of referral confirmations.
  src/miner.cpp
  src/miner.h
  src/txmempool.cpp
  src/txmempool.h
Labels: bug, major, mining, ready for review

#345 Fix ambassador lottery sampling.
  src/pog/select.cpp
  src/pog/select.h
  src/validation.cpp
Labels: bug, major, mining, ready for review

#347 Fix GlobalSend transactions.
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/miner.cpp
  src/txmempool.cpp
  src/validation.cpp
Labels: bug, major, mining, ready for review

#350 Plural of Merit is Merit
  src/coins.h
  src/qt/askpassphrasedialog.cpp
  src/qt/locale/merit_af.ts
  src/qt/locale/merit_ar.ts
  src/qt/locale/merit_be_BY.ts
  src/qt/locale/merit_bg.ts
  src/qt/locale/merit_ca.ts
  src/qt/locale/merit_ca@valencia.ts
  src/qt/locale/merit_ca_ES.ts
  src/qt/locale/merit_cs.ts
  src/qt/locale/merit_da.ts
  src/qt/locale/merit_de.ts
  src/qt/locale/merit_en.ts
  src/qt/locale/merit_en_GB.ts
  src/qt/locale/merit_es.ts
  src/qt/locale/merit_es_ES.ts
  src/qt/locale/merit_et.ts
  src/qt/locale/merit_eu_ES.ts
  src/qt/locale/merit_fi.ts
  src/qt/locale/merit_fr.ts
  src/qt/locale/merit_fr_FR.ts
  src/qt/locale/merit_he.ts
  src/qt/locale/merit_id_ID.ts
  src/qt/locale/merit_it.ts
  src/qt/locale/merit_ja.ts
  src/qt/locale/merit_ko_KR.ts
  src/qt/locale/merit_ms_MY.ts
  src/qt/locale/merit_nb.ts
  src/qt/locale/merit_ne.ts
  src/qt/locale/merit_nl.ts
  src/qt/locale/merit_pl.ts
  src/qt/locale/merit_pt_BR.ts
  src/qt/locale/merit_pt_PT.ts
  src/qt/locale/merit_ru.ts
  src/qt/locale/merit_sk.ts
  src/qt/locale/merit_sl_SI.ts
  src/qt/locale/merit_sr@latin.ts
  src/qt/locale/merit_sv.ts
  src/qt/locale/merit_tr.ts
  src/qt/locale/merit_uk.ts
  src/qt/locale/merit_zh_CN.ts
  src/qt/locale/merit_zh_HK.ts
  src/qt/locale/merit_zh_TW.ts
  src/qt/meritunits.cpp
  src/qt/receivecoinsdialog.h
  src/qt/sendcoinsdialog.h
  src/qt/sendcoinsentry.h
  src/wallet/rpcwallet.cpp
Labels: ready for review

#349 Mnemonic Encryption
  src/qt/importwalletdialog.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/qt/walletview.cpp
  src/qt/walletview.h
  src/wallet/crypter.cpp
  src/wallet/crypter.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: WIP, bug, major

#351 Adding clearer text and UI for selecting download option.
  src/qt/faststart.cpp
  src/qt/faststart.h
  src/qt/forms/faststart.ui
Labels: Feature Request, enhancement, ready for review

#354 Licenses for cuckoo package
  src/cuckoo/LICENSE.md
  src/cuckoo/README.md
  src/cuckoo/cuckoo.cpp
  src/cuckoo/cuckoo.h
  src/cuckoo/mean_cuckoo.cpp
  src/cuckoo/mean_cuckoo.h
  src/cuckoo/miner.cpp
  src/cuckoo/miner.h
Labels: ready for review

#353 Update README
  README.md
Labels: documentation, ready for review

#359 Fix network difficulty calculation
  src/rpc/blockchain.cpp
Labels: ready for review

#355 Improve getmininginfo numbers.
  src/cuckoo/miner.cpp
  src/cuckoo/miner.h
  src/miner.cpp
  src/net.cpp
  src/net.h
  src/rpc/client.cpp
  src/rpc/mining.cpp
Labels: enhancement, ready for review

#294 Pool mining
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/validation.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: ready for review
