Repository meritlabs/merit, pull requests merged in 2018-07, with the labels that each got.

#376 Add data argument to sendtoaddress call
  src/wallet/rpcwallet.cpp
Labels: ready for review

#383 Detailed Balance
  src/rpc/misc.cpp
Labels: CLI, enhancement, ready for review

#387 Fix serialization size for CUnspentAddressKey
  src/addressindex.h
Labels: bug, ready for review
