Repository meritlabs/merit, pull requests merged in 2018-04, with the labels that each got.

#299 Code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, ready for review

#288 Fast Start
  configure.ac
  depends/config.site.in
  depends/packages/libarchive.mk
  depends/packages/packages.mk
  depends/patches/libarchive/libarchive-1-fixes.patch
  doc/build-osx.md
  src/Makefile.qt.include
  src/Makefile.qttest.include
  src/chainparams.cpp
  src/chainparams.h
  src/qt/faststart.cpp
  src/qt/faststart.h
  src/qt/forms/faststart.ui
  src/qt/forms/intro.ui
  src/qt/forms/modaloverlay.ui
  src/qt/intro.cpp
  src/qt/merit.cpp
  src/qt/modaloverlay.cpp
  src/qt/overviewpage.cpp
Labels: enhancement, ready for review

#311 Fix GUI not filtering out the @ symbol properly.
  src/primitives/referral.cpp
  src/primitives/referral.h
  src/qt/faststart.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: ready for review

#313 Fix qt default version and docs
  build-aux/m4/merit_qt.m4
  configure.ac
  doc/build-osx.md
  doc/build-unix.md
Labels: bug, ready for review

#314 Fix libarchive includes for building qt in macos
  src/Makefile.qt.include
Labels: bug, ready for review

#315 make getrawtransactions not do slow search by default.
  src/rpc/rawtransaction.cpp
  src/validation.cpp
Labels: enhancement, ready for review

#316 Qt - disable "Export wallet" for wallets with no mnemonic
  src/qt/meritgui.cpp
  src/qt/meritgui.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: bug, ready for review

#312 Show cleaned up alias in the rpc and UI.
  src/primitives/referral.cpp
  src/primitives/referral.h
  src/qt/referralrecord.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/wallet/wallet.h
Labels: bug, ready for review

#318 Don't allow slow search for transactions in validation.
  src/validation.cpp
Labels: enhancement, ready for review

#289 Add node hashpower information
  src/cuckoo/mean_cuckoo.cpp
  src/cuckoo/mean_cuckoo.h
  src/cuckoo/miner.cpp
  src/cuckoo/miner.h
  src/miner.cpp
  src/miner.h
  src/net.cpp
  src/net.h
  src/primitives/block.h
  src/rpc/mining.cpp
Labels: enhancement, ready for review

#323 Fix sending invites to same address
  src/qt/transactiontablemodel.cpp
  src/validation.cpp
Labels: bug, ready for review

#324 Fix invite coin control when wallet has many keys.
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: bug, major, ready for review

#326 Fix the Travis CI build
  .travis.yml
Labels: WIP

#328 Confirmed status was not set to false on startup.
  src/qt/walletmodel.cpp
Labels: bug, ready for review

#325 Amount field for Invite notifications display number of invites instead of MRT
  src/qt/meritgui.cpp
  src/qt/meritunits.cpp
  src/qt/walletview.cpp
Labels: Qt Wallet, ready for review

#329 Show aliases for transactions.
  src/qt/addresstablemodel.cpp
  src/qt/meritgui.cpp
  src/qt/meritgui.h
  src/qt/overviewpage.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactionfilterproxy.cpp
  src/qt/transactionfilterproxy.h
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/qt/transactiontablemodel.h
  src/qt/transactionview.cpp
  src/qt/transactionview.h
  src/qt/walletview.cpp
  src/qt/walletview.h
  src/referrals.cpp
  src/referrals.h
  src/validation.cpp
  src/validation.h
Labels: enhancement, ready for review

#332 Add support for invites and beacons during rescan.
  src/wallet/wallet.cpp
Labels: bug, ready for review

#333 Don't show enabling invite in listinvites.
  src/wallet/rpcwallet.cpp
Labels: enhancement, ready for review, usability

#321 Starting mining from cli does not trigger interface changes
  src/qt/meritgui.cpp
  src/qt/meritgui.h
  src/rpc/mining.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/ui_interface.h
Labels: CLI, Qt Wallet, bug, ready for review

#319 add bip39 checksum to entropy when picking mnemonic words
  src/crypto/mnemonic/mnemonic.cpp
  src/crypto/mnemonic/mnemonic.h
  src/wallet/wallet.cpp
Labels: ready for review

#335 Cleanup warnings.
  src/blockencodings.cpp
  src/crypto/mnemonic/mnemonic.cpp
  src/cuckoo/mean_cuckoo.cpp
  src/miner.cpp
  src/qt/faststart.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/walletmodel.cpp
  src/rpc/mining.cpp
  src/validation.cpp
  src/wallet/wallet.cpp
Labels: enhancement, ready for review

#336 Fix for windows checksum failure.
  src/serialize.h
  src/undo.h
Labels: ready for review
