Repository meritlabs/merit, pull requests merged in 2018-03, with the labels that each got.

#267 Output number of invites included by the miner.
  src/miner.cpp
Labels: enhancement, ready for review

#268 Undo Data was missing invite metadata information.
  src/undo.h
  src/validation.cpp
Labels: bug, major, ready for review

#270 Ambassador reward filter filter on transactions list view
  src/qt/transactionview.cpp
Labels: ready for review

#272 The miner can package the transactions in the wrong order.
  src/miner.cpp
Labels: bug, ready for review

#274 Invite lottery was broken when disconnecting blocks.
  src/pog/reward.cpp
  src/refdb.cpp
Labels: bug, major, ready for review

#275 Better and Safer Aliases
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/ref_verify.cpp
  src/consensus/ref_verify.h
  src/primitives/referral.cpp
  src/primitives/referral.h
  src/qt/enterunlockcode.cpp
  src/refdb.cpp
  src/refdb.h
  src/referrals.cpp
  src/referrals.h
  src/refmempool.cpp
  src/refmempool.h
  src/rpc/misc.cpp
  src/rpc/rawreferral.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/wallet.cpp
  src/wallet/walletdb.cpp
Labels: major, ready for review

#276 Added simple slides describing benefits of Merit while the user waits.
  src/Makefile.qt.include
  src/qt/forms/modaloverlay.ui
  src/qt/merit.qrc
  src/qt/modaloverlay.cpp
  src/qt/modaloverlay.h
  src/qt/res/icons/community.png
  src/qt/res/icons/hourglass.png
  src/qt/res/icons/safety.png
  src/qt/res/icons/simplicity.png
  src/qt/res/src/community.svg
  src/qt/res/src/hourglass.svg
  src/qt/res/src/safety.svg
  src/qt/res/src/simplicity.svg
Labels: enhancement, ready for review

#278 Fix confusing transition between reindexing and downloading.
  src/qt/forms/modaloverlay.ui
  src/qt/modaloverlay.cpp
  src/qt/modaloverlay.h
  src/qt/overviewpage.cpp
Labels: enhancement, ready for review

#271 Daedalus is infinite on testnet
  src/chainparams.cpp
Labels: ready for review

#280 Feature/correct disconnect order for invites
  src/chainparams.cpp
  src/chainparams.h
  src/checkpoints.cpp
  src/pog/select.cpp
  src/undo.h
  src/validation.cpp
  src/validation.h
Labels: bug, ready for review

#285 Adding support for proper script multi sig addresses
  src/merit-tx.cpp
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/script/interpreter.h
  src/script/sign.cpp
  src/wallet/rpcwallet.cpp
Labels: bug, enhancement, ready for review

#265 Feature - mnemonic support
  src/Makefile.am
  src/crypto/mnemonic/dictionary.cpp
  src/crypto/mnemonic/dictionary.h
  src/crypto/mnemonic/mnemonic.cpp
  src/crypto/mnemonic/mnemonic.h
  src/crypto/pkcs5_pbkdf2.cpp
  src/crypto/pkcs5_pbkdf2.h
  src/key.cpp
  src/rpc/protocol.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.h
Labels: ready for review

#284 Add a getcommunityinfo rpc call
  src/wallet/rpcwallet.cpp
Labels: ready for review

#290 Bug - mnemonic dictionary sometimes fails to link
  src/crypto/mnemonic/dictionary.cpp
  src/crypto/mnemonic/dictionary.h
  src/wallet/wallet.cpp
Labels: bug, ready for review

#256 Qt/backup wallet with qrcode
  src/Makefile.qt.include
  src/qt/exportwalletdialog.cpp
  src/qt/exportwalletdialog.h
  src/qt/forms/exportwalletdialog.ui
  src/qt/forms/receiverequestdialog.ui
  src/qt/meritgui.cpp
  src/qt/meritgui.h
  src/qt/qrimagewidget.cpp
  src/qt/qrimagewidget.h
  src/qt/qrutil.h
  src/qt/receiverequestdialog.cpp
  src/qt/receiverequestdialog.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: ready for review

#293 Add qrencode library to merit OSX docs
  doc/build-osx.md
Labels: enhancement, ready for review

#291 Preallocate memory for UTXO list
  src/rpc/misc.cpp
  src/univalue/include/univalue.h
  src/univalue/lib/univalue.cpp
  src/validation.cpp
Labels: ready for review

#295 Qt - decline pending invites
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/referrallistmodel.cpp
  src/qt/referrallistmodel.h
  src/qt/referralrecord.cpp
  src/qt/referralrecord.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: Qt Wallet, enhancement, ready for review

#287 Fix potential exploit of leapfrogging invites.
  src/init.cpp
  src/miner.cpp
  src/net_processing.cpp
  src/pog/select.cpp
  src/pog/select.h
  src/primitives/referral.cpp
  src/refdb.cpp
  src/refdb.h
  src/referrals.cpp
  src/referrals.h
  src/rpc/misc.cpp
  src/txdb.cpp
  src/txdb.h
  src/validation.cpp
  src/validation.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: bug, ready for review

#300 Fix block state time getter for miner
  src/chainparams.cpp
  src/chainparams.h
  src/pog/reward.cpp
  src/primitives/block.cpp
Labels: bug, ready for review

#301 Fix resize for the invites sent list.
  src/qt/forms/overviewpage.ui
Labels: bug, ready for review
